sudo: false

env:
  global:
    - NODE_ENV=production
    - GLOBAL_DATE=$(date +%Y-%m-%d)

language: node_js

node_js:
  - '6'
  - '8'
  - '10'
  - 'node'

# https://docs.travis-ci.com/user/caching
cache:
  directories:
    - ./node_modules/

install:
  - npm ci --production=false

script:
  - npm run lint && npm test
