sudo: false

env:
  global:
    - NODE_ENV=production
    - GLOBAL_DATE=$(date +%Y-%m-%d)

language: node_js

node_js:
  - '8'

cache: yarn

install:
  - yarn --no-progress --prefer-offline --check-files --production=false

script:
  - yarn run lint && yarn test
